server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://150.158.15.4:3306/geekbang_coupon_db?useSSL=false&&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml